### ISSUE TITLE
0-RTT

### ISSUE THREAD

**Issue by mcmanus** [mcmanus/mozquic#25]

**Comment by ddragana** [comment]
taking this

**Comment by ddragana** [comment]
Current implementation at https://github.com/ddragana/mozquic/tree/0RTT

**Comment by mcmanus** [comment]
a lot of this is currently checked in

notes on the remainder https://docs.google.com/document/d/1jWc2gEVrFiDYYkQFWTLODguhmzEBcnsI5qKOrM8Q8_g/edit

need to fix max-early-data.. which can only be done when we move to -23.. dep on https://bugzilla.mozilla.org/show_bug.cgi?id=1427556

-08 is a bit broken because we cannot deal with transport parameters and NST - but https://github.com/quicwg/base-drafts/issues/1015 is expected to make that irrelevant

exporting session tickets for persistence would be useful, but is not required atm and hopefully we can leverage gecko for the same feature also blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1399439

**Comment by mcmanus** [comment]
max_early_data bit is done.. 

we still need to honor initial_max_data which means storing the resumption token along with that info. https://hg.mozilla.org/projects/nss/rev/21b6e41668f6275f10a9667b51c01deecb8ad8ca
SSL_SetResumptionTokenCallback() et all

also address validation is required upon resumption, but particularly 0rtt
SSL_SendSessionTicket looks like it can do add a token to the NST for this purpose.

**Comment by mcmanus** [comment]
nonetheless 0rtt ~works so I'll close this and open 2 followons

**Comment by mcmanus** [comment]
see #88 and #89
