### ISSUE TITLE
Change frame header to a variable-length integer encoding where needed

### ISSUE THREAD

**Issue by ddragana** [mcmanus/mozquic#76]
I do not think all frame headers, almost non, use  a variable-length integer encoding. Maybe only acks does.

**Comment by ddragana** [comment]
I will work on this.

**Comment by mcmanus** [comment]
don't most of them? e.g. the flow control ones do.. and things like the
length in the close frame, etc..

**Comment by ddragana** [comment]
I notice some of them yesterday, like rst stream...

Looking at DecodeVarint in Packetization.cpp I see it only for ack frame.
Have you forgot to push something :).

**Comment by ddragana** [comment]
I mean "looking for DecodeVarint..."

**Comment by mcmanus** [comment]
I have only converted the ack frame to use varint.. the others are todo. is
that what you mean? (I figured we would convert the encoder and decoder for
each frame in lockstep so at least the tests would still work with
themselves.)
