### ISSUE TITLE
Server does not send transport parameters in Handshake message

### ISSUE THREAD

**Issue by djc** [mcmanus/mozquic#92]
Testing against your `mozquic.ducksong.com:4433` endpoint, it does not appear to do this.

**Comment by mcmanus** [comment]
but it does :)

can you reconfirm or help provide me some information to track it down? (CID? packet trace with exported keys?)

**Comment by djc** [comment]
Hmm, I probably didn't understand TLS enough yet when I filed this bug. I tested again and I now see your server sending transport parameters just fine. Sorry for the noise!
